name: Backend CI
run-name: Running all verifications of backend
on: [push]

defaults:
  run:
    working-directory: ./backend

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'
      - name: Check if code is formatted
        run: mvn spotless:check
      - name: Run verify suit
        run : mvn verify -Dspring.flyway.enabled=false
      - name: Archive development documentation
        run: |
          echo ::group::Archive artifact
          tar \
            --dereference --hard-dereference \
            --directory "$INPUT_PATH" \
            -cvf "$RUNNER_TEMP/github-pages.tar" \
            --exclude=.git \
            --exclude=.github \
            .
          echo ::endgroup::
        env:
          INPUT_PATH: target/generated-docs
      - name: Upload archive to github pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: ${{ runner.temp }}

  deploy-dev-docs:
    runs-on: ubuntu-latest
    needs: check
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


