name: Backend CI
run-name: Running all verifications of backend
on: [push]

defaults:
  run:
    working-directory: ./backend

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'
      - name: Check if code is formatted
        run: mvn spotless:check
      - name: Run verify suit
        run : mvn verify -Dspring.flyway.enabled=false
