name: Backend CI
run-name: Running all verifications of backend
on: [push]

defaults:
  run:
    working-directory: ./backend

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'
      - name: Check if code is formatted
        run: mvn spotless:check
      
      - name: Run verify suit
        run : mvn verify -Dspring.flyway.enabled=false
      
      - name: Upload archive to github pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: backend/target/generated-docs
        
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/testCoverage/testCoverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80

      - name: Informs that PR has fail when coverage is less then 80%
        if: ${{ steps.jacoco.outputs.coverage-overall < 80.0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Cobertura geral é menor que 80%!')    

  deploy-dev-docs:
    runs-on: ubuntu-latest
    needs: check
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


