name: Backend CI
run-name: Running all verifications of backend
on: [push]

defaults:
  run:
    working-directory: ./backend

jobs:
  check:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'
      - name: Run verify suit
        run : ./mvnw verify -Dspring.flyway.enabled=false
      - name: Check if code is formatted
        run: ./mvnw spotless:check
      - name: Upload archive to github pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: backend/target/generated-docs

  deploy-dev-docs:
    runs-on: ubuntu-latest
    needs: check
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


