name: Backend CI
run-name: Running all verifications of backend
on: [push]

defaults:
  run:
    working-directory: ./backend

jobs:
  changes:
      runs-on: ubuntu-latest
      outputs:
        docs : ${{ steps.filter.outputs.docs }}
      steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docs:
              - 'backend/src/docs/asciidoc/**'

  check:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: borapagar
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'
      
      - name: Run verify suit
        run : ./mvnw verify
      
      - name: Check if code is formatted
        run: ./mvnw spotless:check
      
      
      - name: Upload archive to github pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: backend/target/generated-docs
    
  test-coverage:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: borapagar
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'

      - name: Generate coverage report
        run: ./mvnw test
          
      - name: Add coverage to PR
        id: jacoco
        uses: Madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/backend/target/site/jacoco/jacoco.xml 
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          title: 'Relatório de cobertura'
          update-comment: true
          skip-if-no-changes: false
          pass-emoji: ':ok_hand:'
          fail-emoji: ':skull_and_crossbones:'
          continue-on-error: true
          debug-mode: false

      - name: Informs that PR has fail when coverage is less then 40%
        if: ${{ steps.jacoco.outputs.coverage-overall < 40.0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Cobertura geral é menor que 40%!')    

  deploy-dev-docs:
    runs-on: ubuntu-latest
    needs: [check, changes]
    if: ${{ needs.changes.outputs.docs == 'true' }}
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


