name: Backend CI
run-name: Running all verifications of backend
on: 
  push:
    paths:
      - 'backend/**'

defaults:
  run:
    working-directory: ./backend

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Compile Project with Maven
        run: mvn clean compile
      - name: Check if code is formatted
        run: mvn spotless:check
      - name: Run tests
        run: mvn test
      - name: Verify for errors and bugs
        run : mvn verify
