name: Test Coverage

on:
  pull_request:

jobs:
  
 test-coverage:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: borapagar
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v1
        with:
          java-version: '21'
      
      - name: Generate test coverage
        run: ./mvnw test

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/backend/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60

      - name: Informs that PR has fail when coverage is less then 40%
        if: ${{ steps.jacoco.outputs.coverage-overall < 40.0 }}
        uses: actions/github-script@v6
        with:
            script: |
                core.setFailed('Cobertura geral é menor que 40%!')